name: Run Tests

on:
  push:
    branches: [ "main", "ci-testing" ]

permissions:
  contents: read

jobs:
  test-all-extras:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v3
    - name: Install dependencies
      run: rye sync
    - name: Run tests
      run: rye test
    - name: Run invariant.examples
      run: rye run python -m unittest discover -s invariant/examples -p "*_example.py"
  test-no-extras:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v3
    - name: Install dependencies
      run: rye sync --no-dev
    - name: Run tests
      # use 'unittest' explicitly, to prevent rye from install dev dependencies (no extras run)
      run: rye run python -m unittest discover tests
