name: Run Tests (all extras)

on:
  push:
    branches: [ "main", "ci-testing" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v3
      with:
        enable-cache: true
    - name: Install dependencies
      run: rye sync
    - name: Run tests
      run: rye test
